<?xml version="1.0"?>

<!-- rosrun xacro xacro panda_multiple_arms.xacro -o panda_multiple_arms.urdf -->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="walls">
  <xacro:macro name="walls_world">
    <xacro:property name="length" value="10.0" /> 
    <xacro:property name="width" value="0.1" /> 
    <xacro:property name="height" value="1" /> 


    <link name="world_center"/>

    <link name="world"/>

    <joint name="world_center_to_world" type="fixed">
      <parent link="world_center"/>
      <child link="world"/>
      <origin rpy="0 0 0" xyz="${-length/2} ${-length/2} 0"/>
    </joint>

    

    <!-- Setup the first wall -->
    <link name="wall_right" type="fixed">
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="${length/2} 0 0"/>
      </visual>
    </link>

    <joint name="world_to_right" type="fixed">
      <parent link="world"/>
      <child link="wall_right"/>
      <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
    </joint>

    <!-- Setup the second wall -->
    <link name="wall_front">
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="${length/2} 0 0"/>
      </visual>
    </link>

    <joint name="right_to_front" type="fixed">
      <parent link="wall_right"/>
      <child link="wall_front"/>
      <origin rpy="0 0 1.5708" xyz="${length} 0 0"/>
    </joint>

    <!-- Setup the third wall -->
    <link name="wall_left">
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="${length/2} 0 0"/>
      </visual>
    </link>

    <joint name="front_to_left" type="fixed">
      <parent link="wall_front"/>
      <child link="wall_left"/>
      <origin rpy="0 0 1.5708" xyz="${length} 0 0"/>
    </joint>


    <!-- Setup the fourth wall -->
    <link name="wall_back">
      <visual>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="${length/2} 0 0"/>
      </visual>
    </link>

    <joint name="left_to_back" type="fixed">
      <parent link="wall_left"/>
      <child link="wall_back"/>
      <origin rpy="0 0 1.5708" xyz="${length} 0 0"/>
    </joint>


    <!-- Shelf properties -->
    <xacro:property name="shelf_length" value="1" /> 
    <xacro:property name="shelf_width" value="2" /> 
    <xacro:property name="shelf_height" value="0.3" /> 

    <!-- Setup the first shelf -->
    <link name="shelf_1">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_1" type="fixed">
      <parent link="world"/>
      <child link="shelf_1"/>
      <origin rpy="0 0 0" xyz="${1*length/4} ${length/3} 0"/>
    </joint>


    <!-- Setup the second shelf -->
    <link name="shelf_2">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_2" type="fixed">
      <parent link="world"/>
      <child link="shelf_2"/>
      <origin rpy="0 0 0" xyz="${2*length/4} ${length/3} 0"/>
    </joint>

    <!-- Setup the third shelf -->
    <link name="shelf_3">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_3" type="fixed">
      <parent link="world"/>
      <child link="shelf_3"/>
      <origin rpy="0 0 0" xyz="${3*length/4} ${length/3} 0"/>
    </joint>

    <!-- Setup the fourth shelf -->
    <link name="shelf_4">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_4" type="fixed">
      <parent link="world"/>
      <child link="shelf_4"/>
      <origin rpy="0 0 0" xyz="${1*length/4} ${2*length/3} 0"/>
    </joint>


    <!-- Setup the fifth shelf -->
    <link name="shelf_5">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_5" type="fixed">
      <parent link="world"/>
      <child link="shelf_5"/>
      <origin rpy="0 0 0" xyz="${2*length/4} ${2*length/3} 0"/>
    </joint>

    <!-- Setup the sixth shelf -->
    <link name="shelf_6">
      <visual>
        <geometry>
          <box size="${shelf_length} ${shelf_width} ${shelf_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${shelf_height/2}"/>
      </visual>
    </link>

    <joint name="world_to_shelf_6" type="fixed">
      <parent link="world"/>
      <child link="shelf_6"/>
      <origin rpy="0 0 0" xyz="${3*length/4} ${2*length/3} 0"/>
    </joint>


    <!-- ############# -->
    <!-- Pickup points -->
    <!-- ############# -->
    <xacro:property name="pp_length" value="0.5" /> 
    <xacro:property name="pp_width" value="0.5" /> 
    <xacro:property name="pp_height" value="${height*1.3}" /> 

    <material name="pickup_shelf_color">
      <color rgba="0.5 0.5 0.5 0.99"/>
    </material>

    <xacro:macro name="pickup_point" params="number loc_x loc_y">
      <link name="pickup_point_${number}">
        <visual>
          <geometry>
            <box size="${pp_length} ${pp_width} ${pp_height}"/>
          </geometry>
          <origin rpy = "0 0 0" xyz="0 0 ${pp_height/2}"/>
          <!-- <material> -->
            <!-- <color rgba="0.2 0.2 0.2 1"/> -->
          <!-- </material> -->
          <!-- <color rgba="1 1 1 1"/> -->
          <material name="pickup_shelf_color"/>
        </visual>
      </link>

      <joint name="world_to_pickup_point_${number}" type="fixed">
        <parent link="world"/>
        <child link="pickup_point_${number}"/>
        <origin rpy="0 0 0" xyz="${loc_x} ${loc_y} 0"/>
      </joint>      
    </xacro:macro>

    <xacro:pickup_point number="1" loc_x="${length/4}" loc_y="0"/>
    <xacro:pickup_point number="2" loc_x="${2*length/4}" loc_y="0"/>
    <xacro:pickup_point number="3" loc_x="${3*length/4}" loc_y="0"/>

    <xacro:pickup_point number="4" loc_x="0" loc_y="${length/4}"/>
    <xacro:pickup_point number="5" loc_x="0" loc_y="${2*length/4}"/>
    <xacro:pickup_point number="6" loc_x="0" loc_y="${3*length/4}"/>

    <xacro:pickup_point number="7" loc_x="${length/4}" loc_y="${length}"/>
    <xacro:pickup_point number="8" loc_x="${2*length/4}" loc_y="${length}"/>
    <xacro:pickup_point number="9" loc_x="${3*length/4}" loc_y="${length}"/>

    <!-- ############# -->
    <!-- Dropoff point -->
    <!-- ############# -->

    <link name="dropoff_point">
      <visual>
        <geometry>
          <box size="${pp_length} 2 ${pp_height}"/>
        </geometry>
        <origin rpy = "0 0 0" xyz="0 0 ${pp_height/2}"/>
        <!-- <material name="pickup_shelf_color"/> -->
      </visual>
    </link>

    <joint name="world_to_dropoff_point" type="fixed">
      <parent link="world"/>
      <child link="dropoff_point"/>
      <origin rpy="0 0 0" xyz="${length} ${length/2} 0"/>
    </joint>


  </xacro:macro>
  <!-- <xacro:walls_world/> -->
</robot>